config/routes.rb
Workarea::Storefront::Engine.routes.draw do
  resource :ge_checkout, only: :show
  get 'get-checkout-cart-info', to: 'global_e#get_checkout_cart_info', as: 'global_e_checkout_cart_info'

  namespace :globale do
    post :receive_order, controller: :api
    # TODO hack alias
    post :performorderpayment, to: 'api#receive_payment'
    post :receive_payment, controller: :api
    post :update_order_status, controller: :api
    post :receive_shipping_info, controller: :api
    post :remove_restricted_products, controller: :api
    post :receive_order_refund, controller: :refund
  end
end

Workarea::Admin::Engine.routes.draw do
  resources :orders, only: [] do
    member do
      get :global_e
    end
  end

  resources :pricing_skus, only: [] do
    resources :fixed_prices, except: :show
  end

  resources :catalog_products, only: [] do
    resources :country_exceptions, except: :show
  end
end

app/models/workarea/global_e/fixed_price.rb
module Workarea
  module GlobalE
    class FixedPrice
      include ApplicationDocument
      include Releasable

      field :country, type: Country
      field :currency_code, type: String
      field :regular, type: Money
      field :sale, type: Money
      field :msrp, type: Money

      embedded_in :pricing_sku, inverse_of: :fixed_prices

      validates_presence_of :regular, :currency
      validate :validate_foreign_currency
      validate :valid_currency
      validate :currencies_match
      validate :unique_currency
      validate :unique_country

      delegate :on_sale?, to: :pricing_sku

      def currency
        Money::Currency.find currency_code
      end

      def sell
        if on_sale? && sale.present?
          sale
        else
          regular
        end
      end

      private

        def validate_foreign_currency
          if regular.present? && regular.currency == Money.default_currency
            errors.add(:regular, I18n.t('workarea.fixed_price.errors.invalid_fixed_price_currency'))
          end

          if sale.present? && sale.currency == Money.default_currency
            errors.add(:sale, I18n.t('workarea.fixed_price.errors.invalid_fixed_price_currency'))
          end
        end

        def valid_currency
          return unless currency_code.present?

          if Money::Currency.find(currency_code).blank?
            errors.add(:currency_code, I18n.t('workarea.fixed_price.errors.invalid_currency'))
          end
        end

        def currencies_match
          if currency.present? && regular.present? && regular.currency != currency
            errors.add(:base, I18n.t('workarea.fixed_price.errors.currency_and_regular_mistmatch'))
          end

          if sale.present? && regular.present? && regular.currency != sale.currency
            errors.add(:base, I18n.t('workarea.fixed_price.errors.sale_and_regular_currency_mismatch'))
          end
        end

        def unique_currency
          return unless pricing_sku.present? && currency_code.present?

          currency_exists = pricing_sku.fixed_prices.any? do |fixed_price|
            fixed_price != self &&
              fixed_price.currency_code == currency_code &&
              fixed_price.country == country
          end

          if currency_exists
            errors.add(:base, I18n.t('workarea.fixed_price.errors.currency_must_be_unique'))
          end
        end

        def unique_country
          return unless pricing_sku.present? && country.present?

          country_exists = pricing_sku.fixed_prices.any? do |fixed_price|
            fixed_price != self && fixed_price.country == country
          end

          if country_exists
            errors.add(:base, I18n.t('workarea.fixed_price.errors.country_must_be_unique'))
          end
        end
    end
  end
end

app/controllers/workarea/admin/fixed_prices_controller.rb
module Workarea
  module Admin
    class FixedPricesController < ApplicationController
      required_permissions :catalog
      helper GlobalEHelpers

      before_action :find_sku
      before_action :find_price, except: [:index, :new]

      def index
      end

      def new
        @fixed_price = GlobalE::FixedPrice.new(fixed_price_params)
      end

      def create
        if @fixed_price.save
          flash[:success] = t('workarea.admin.fixed_prices.flash_messages.saved', sku: @sku.id)
          redirect_to pricing_sku_fixed_prices_path(@sku)
        else
          @sku.reload
          flash.now[:error] = t('workarea.admin.fixed_prices.flash_messages.create_error')
          render :new
        end
      end

      def edit
      end

      def update
        if @fixed_price.update_attributes(fixed_price_params)
          flash[:success] = t('workarea.admin.fixed_prices.flash_messages.saved', sku: @sku.id)
          redirect_to pricing_sku_fixed_prices_path(@sku)
        else
          flash.now[:error] = t('workarea.admin.fixed_prices.flash_messages.update_error')
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        @fixed_price.destroy

        flash[:success] = t('workarea.admin.fixed_prices.flash_messages.deleted', sku: @sku.id)
        redirect_to pricing_sku_fixed_prices_path(@sku)
      end

      private

        def fixed_price_params
          @fixed_price_params ||=
            begin
              permitted = params.fetch(:fixed_price, {}).permit(:country, :currency_code, :sale, :regular, :active)
              currency_code = permitted[:currency_code]

              permitted[:regular] =
                if permitted[:regular].present? && currency_code.present?
                  permitted[:regular].to_m(currency_code)
                else
                  nil
                end

              permitted[:sale] =
                if permitted[:sale].present? && currency_code.present?
                  permitted[:sale].to_m(currency_code)
                else
                  nil
                end

              permitted
            end
        end

        def find_sku
          @sku = PricingSkuViewModel.wrap(
            Pricing::Sku.find(params[:pricing_sku_id])
          )
        end

        def find_price
          @fixed_price = if params[:id].present?
                     @sku.fixed_prices.find_or_create_by(id: params[:id])
                   else
                     @sku.fixed_prices.build(fixed_price_params)
                   end
        end
    end
  end
end

app/views/workarea/admin/fixed_prices/edit.html.haml
- @page_title = t('workarea.admin.fixed_prices.title', sku: @sku.name)

.view
  .view__header
    .grid
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@sku)
          %h1= link_to @sku.name, url_for(@sku)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@sku)

  .view__container
    = render_cards_for(@sku, :fixed_prices)

  .view__container.view__container
    = form_tag pricing_sku_fixed_price_path(@sku, @fixed_price), method: :patch, data: { unsaved_changes: '' } do
      = hidden_field_tag "fixed_price[currency_code]", @fixed_price.currency.iso_code

      %table
        %thead
          %tr
            %th= t('workarea.admin.fixed_prices.country')
            %th= t('workarea.admin.fixed_prices.regular_price')
            %th #{t('workarea.admin.fixed_prices.sale_price')} #{t('workarea.admin.fixed_prices.sale_price_default')}
            %th= t('workarea.admin.fixed_prices.msrp')
            %th
              = t('workarea.admin.fields.active')
              = inline_svg('workarea/admin/i18n.svg', class: 'svg-icon svg-icon--small') if locale_options.many? && Workarea.config.localized_active_fields
            %th
            %th
        %tbody
          - @sku.fixed_prices.each do |fixed_price|
            - if fixed_price.id == @fixed_price.id
              %tr
                %td
                  = select_tag "fixed_price[country]", options_for_select(global_e_country_options, @fixed_price.country&.alpha2), title: t('workarea.admin.field.country')
                %td
                  %span.currency_symbol= fixed_price.currency.symbol
                  = text_field_tag 'fixed_price[regular]', fixed_price.regular, class: 'text-box text-box--small', title: t('workarea.admin.fields.regular'), id: "fixed_price[regular]"
                %td
                  %span.currency_symbol= fixed_price.currency.symbol
                  = text_field_tag 'fixed_price[sale]', fixed_price.sale, class: 'text-box text-box--small', title: t('workarea.admin.fields.sale'), id: "fixed_price[sale]"
                %td
                  - if fixed_price.msrp
                    %span.currency_symbol= fixed_price.currency.symbol
                    = text_field_tag 'fixed_price[msrp]', fixed_price.msrp, class: 'text-box text-box--small', title: t('workarea.admin.fields.msrp'), id: "fixed_price[msrp]"
                %td
                  = toggle_button_for 'fixed_price[active]', @fixed_price.active?
                %td
                %td
            - else
              %tr
                %td= fixed_price.country
                %td= number_to_currency(fixed_price.regular)
                %td= number_to_currency(fixed_price.sale)
                %td
                  - if fixed_price.msrp
                    = number_to_currency(fixed_price.msrp)
                %td
                  - if fixed_price.active?
                    = t('workarea.admin.fixed_prices.active')
                  - else
                    = t('workarea.admin.fixed_prices.inactive')
                %td
                %td

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= render 'workarea/admin/shared/publishing_select'
          .grid__cell= button_tag t('workarea.admin.form.save_changes'), value: 'save_fixed_price', class: 'workflow-bar__button workflow-bar__button--update'

app/views/workarea/admin/fixed_prices/index.html.haml
- @page_title = t('workarea.admin.fixed_prices.title', sku: @sku.name)

.view
  .view__header
    .grid
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@sku)
          %h1= link_to @sku.name, url_for(@sku)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@sku)

  .view__container
    = render_cards_for(@sku, :fixed_prices)

  .view__container.view__container--narrow
    %table
      %thead
        %tr
          %th= t('workarea.admin.fixed_prices.currency')
          %th= t('workarea.admin.fixed_prices.country')
          %th= t('workarea.admin.fixed_prices.regular_price')
          %th #{t('workarea.admin.fixed_prices.sale_price')} #{t('workarea.admin.fixed_prices.sale_price_default')}
          %th= t('workarea.admin.fixed_prices.msrp')
          %th= t('workarea.admin.fields.active')
          %th= t('workarea.admin.fields.on_sale')
          %th
      %tbody
        - @sku.fixed_prices.each do |fixed_price|
          %tr
            %td #{fixed_price.currency} (#{fixed_price.currency.symbol})
            %td= fixed_price.country&.name
            %td= number_to_currency(fixed_price.regular)
            %td= number_to_currency(fixed_price.sale)
            %td
              - if fixed_price.msrp
                = number_to_currency(fixed_price.msrp)
            %td
              - if fixed_price.active?
                = t('workarea.admin.fixed_prices.active')
              - else
                = t('workarea.admin.fixed_prices.inactive')
            %td= fixed_price.on_sale? ? t("workarea.admin.pricing_skus.on_sale") : t("workarea.admin.pricing_skus.not_on_sale")
            %td
              .align-right<
                = link_to edit_pricing_sku_fixed_price_path(@sku, fixed_price), id: dom_id(fixed_price, 'edit_action') do
                  = inline_svg('workarea/admin/icons/edit.svg', class: 'svg-icon svg-icon--small', title: t('workarea.admin.actions.edit'))
                = link_to pricing_sku_fixed_price_path(@sku, fixed_price), id: dom_id(fixed_price, 'delete_action'), data: { method: 'delete', confirm: t('workarea.admin.actions.delete_confirmation') } do
                  = inline_svg('workarea/admin/icons/delete.svg', class: 'svg-icon svg-icon--small svg-icon--red', title: t('workarea.admin.actions.delete'))

    .workflow-bar
      .grid.grid--auto.grid--right.grid--middle
        .grid__cell= link_to t('workarea.admin.fixed_prices.index.button'), new_pricing_sku_fixed_price_path(@sku), id: 'add_pricing_sku_fixed_price', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/fixed_prices/new.html.haml
- @page_title = t('workarea.admin.fixed_prices.title', sku: @sku.name)

.view
  .view__header
    .grid.grid--middle.grid--right
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@sku)
          %h1= link_to @sku.name, url_for(@sku)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@sku)

  .view__container
    = render_cards_for(@sku, :fixed_prices)

  .view__container.view__container
    - @fixed_price.errors.full_messages.each do |message|
      = render_message 'error', message

    %p= t('workarea.admin.fixed_prices.fixed_price_description')

    = form_tag pricing_sku_fixed_prices_path(@sku), method: :post, data: { unsaved_changes: '' } do
      %table
        %thead
          %tr
            %th= t('workarea.admin.fixed_prices.currency')
            %th= t('workarea.admin.fixed_prices.country')
            %th= t('workarea.admin.fixed_prices.regular_price')
            %th= t('workarea.admin.fixed_prices.sale_price')
            %th= t('workarea.admin.fixed_prices.msrp')
            %th= t('workarea.admin.fields.active')
            %th
            %th
        %tbody
          - @sku.fixed_prices.each do |fixed_price, index|
            %tr
              %td #{fixed_price.currency.name} (#{fixed_price.currency.symbol})
              %td= fixed_price.country
              %td= number_to_currency(fixed_price.regular)
              %td= number_to_currency(fixed_price.sale)
              %td
                - if fixed_price.msrp
                  = number_to_currency(fixed_price.msrp)
              %td
                - if fixed_price.active?
                  = t('workarea.admin.fixed_prices.active')
                - else
                  = t('workarea.admin.fixed_prices.inactive')
              %td
              %td

          %tr
            %td
              = select_tag "fixed_price[currency_code]", options_for_select(currency_options, @fixed_price.currency_code), title: t('workarea.admin.fields.currency')
            %td
              = select_tag "fixed_price[country]", options_for_select(global_e_country_options, @fixed_price.country&.alpha2), title:  t('workarea.admin.fields.country')
            %td
              = text_field_tag 'fixed_price[regular]', @fixed_price.regular, class: 'text-box text-box--small', title: t('workarea.admin.fields.regular')
            %td
              = text_field_tag 'fixed_price[sale]', @fixed_price.sale, class: 'text-box text-box--small', title: t('workarea.admin.fields.sale')
            %td
              = text_field_tag 'fixed_price[msrp]', @fixed_price.msrp, class: 'text-box text-box--small', title: t('workarea.admin.fields.msrp')
            %td
              = toggle_button_for 'fixed_price[active]', @fixed_price.active
            %td
            %td

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.fixed_prices.new.create_fixed_price'), value: 'create_fixed_price', class: 'workflow-bar__button workflow-bar__button--create'