config/routes.rb
Workarea::Storefront::Engine.routes.draw do
  resource :ge_checkout, only: :show
  get 'get-checkout-cart-info', to: 'global_e#get_checkout_cart_info', as: 'global_e_checkout_cart_info'

  namespace :globale do
    post :receive_order, controller: :api
    # TODO hack alias
    post :performorderpayment, to: 'api#receive_payment'
    post :receive_payment, controller: :api
    post :update_order_status, controller: :api
    post :receive_shipping_info, controller: :api
    post :remove_restricted_products, controller: :api
    post :receive_order_refund, controller: :refund
  end
end

Workarea::Admin::Engine.routes.draw do
  resources :orders, only: [] do
    member do
      get :global_e
    end
  end

  resources :pricing_skus, only: [] do
    resources :fixed_prices, except: :show
  end

  resources :catalog_products, only: [] do
    resources :country_exceptions, except: :show
  end
end

app/models/workarea/order/status/pending_global_e_fraud_check.rb
module Workarea
  class Order::Status::PendingGlobalEFraudCheck
    include StatusCalculator::Status

    def in_status?
      order.global_e? &&
        order.placed? &&
        order.global_e_approved_at.blank? &&
        !order.canceled?
    end
  end
end

app/views/workarea/admin/orders/_global_e.html.haml
- if order.global_e?
  .grid__cell
    .card{ class: card_classes(:global_e, local_assigns[:active]) }
      = link_to global_e_order_path(order), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.orders.cards.global_e.title')
        = inline_svg 'workarea/admin/i18n.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          %ul.list-reset
            %li
              %strong= t('workarea.admin.orders.cards.global_e.global_e_id')
              = order.global_e_id
            %li
              %strong= t('workarea.admin.orders.cards.global_e.international_subtotal_price')
              = order.international_subtotal_price
            %li
              %strong= t('workarea.admin.orders.cards.global_e.international_shipping_total')
              = order.international_shipping_total
            %li
              %strong= t('workarea.admin.orders.cards.global_e.total_duties_price')
              = number_to_currency order.total_duties_price
            %li
              %strong= t('workarea.admin.orders.cards.global_e.total_price')
              = number_to_currency order.international_total_price
          = link_to global_e_order_path(order), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.orders.cards.global_e.button')

app/views/workarea/admin/orders/attributes.html.haml
- @page_title = t('workarea.admin.orders.attributes.title', name: @order.name)

.view
  .view__header
    .grid.grid--middle.grid--right
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@order)
          %h1= link_to @order.name, url_for(@order)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@order)

  .view__container
    = render_cards_for(@order, :attributes)

  .view__container.view__container--narrow
    .section
      .grid
        .grid__cell.grid__cell--25
          %h2= t('workarea.admin.orders.attributes.checkout.title')
          %ul.list-reset
          - if @order.user.present? || @order.email.present?
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.customer')
              - if @order.user.present?
                = link_to @order.user.name, user_path(@order.user)
              - else
                = @order.email
            - if @order.checkout_by.present? && @order.checkout_by != @order.user
              %li
                %strong
                  = t('workarea.admin.orders.attributes.checkout.placed_by')
                = link_to @order.checkout_by.name, user_path(@order.checkout_by)
            - if @order.source.present?
              %li
                %strong
                  = t('workarea.admin.orders.attributes.checkout.source')
                = @order.source.titleize
            - if @order.copied_from.present?
              %li
                %strong
                  = t('workarea.admin.fields.copied_from_id')
                = link_to @order.copied_from.name, order_path(@order.copied_from)
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.status')
              = @order.model.status.to_s.titleize
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.promo_codes')
              = @order.promo_codes.join(', ').presence || t('workarea.admin.orders.attributes.checkout.none')
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.placed')
              - if @order.placed?
                = local_time_ago(@order.placed_at)
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.ip_address')
              = @order.ip_address.presence || t('workarea.admin.orders.attributes.checkout.none')
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.traffic_referrer')
              = @order.traffic_referrer&.medium.presence || t('workarea.admin.orders.attributes.checkout.none')
            %li
              %strong= t('workarea.admin.orders.attributes.checkout.traffic_referrer_url')
              - if @order.traffic_referrer&.uri.present?
                = link_to t('workarea.admin.orders.attributes.checkout.view'), '#traffic_referrer_url_tooltip', data: { tooltip: { interactive: true, trigger: 'click' }.to_json }
                #traffic_referrer_url_tooltip.tooltip-content
                  .align-center
                    %p= text_field_tag nil, @order.traffic_referrer.uri, id: 'traffic_referrer_url', class: 'text-box'
                    = button_tag t('workarea.admin.orders.attributes.checkout.copy_url'), data: { copy_to_clipboard: '#traffic_referrer_url' }, class: 'button button--small'
              - else
                = t('workarea.admin.orders.attributes.checkout.none')
            %li
              %strong= t('workarea.admin.fields.updated_at')
              #{local_time_ago(@order.updated_at)}
            %li
              %strong= t('workarea.admin.fields.created_at')
              #{local_time_ago(@order.created_at)}
            = append_partials('admin.order_attributes', order: @order)

        .grid__cell.grid__cell--75
          %h2= t('workarea.admin.orders.attributes.items.title')
          %table
            %thead
              %tr
                %th= t('workarea.admin.orders.attributes.items.product')
                %th.align-center= t('workarea.admin.orders.attributes.items.quantity')
                %th.align-right= t('workarea.admin.orders.attributes.items.pricing')
            %tbody
              - @order.items.each do |item|
                %tr
                  %td
                    .grid.grid--auto
                      .grid__cell
                        = link_to image_tag(product_image_url(item.image, :small), alt: item.product.name), catalog_product_url(item.product, sku: item.sku)
                      .grid__cell
                        %p= link_to item.product.name, catalog_product_path(item.product, sku: item.sku)
                        %p= item.sku
                        - if item.customizations.any?
                          - item.customizations.each do |name, value|
                            %p #{name.titleize}: #{value}
                        = append_partials('admin.order_attributes_item_details', item: item)
                  %td.align-center= item.quantity
                  %td.align-right
                    - item.price_adjustments.each do |adjustment|
                      %p
                        %strong= price_adjustment_description_for(adjustment)
                        %span= number_to_currency(adjustment.amount)

          .grid.grid--right
            .grid__cell.grid__cell--50
              %table.data-pairs
                %tbody
                  %tr
                    %th
                      %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.subtotal')
                    %td= number_to_currency @order.subtotal_price
                  - if @order.total_adjustments.any?
                    - @order.total_adjustments.each do |adjustment|
                      %tr
                        %th
                          %span= adjustment.description.titleize
                        %td
                          - if adjustment.discount?
                            %strong= number_to_currency(adjustment.amount)
                          - else
                            %span= number_to_currency(adjustment.amount)
                  %tr
                    %th
                      %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.shipping')
                    %td= number_to_currency @order.shipping_total
                  - if @order.duties_and_taxes_nonsubsidized.present?
                    %tr
                      %th
                        %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.duties_and_taxes_nonsubsidized')
                      %td= number_to_currency @order.duties_and_taxes_nonsubsidized
                  - if @order.duties_and_taxes_subsidized.present?
                    %tr
                      %th
                        %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.duties_and_taxes_subsidized')
                      %td= number_to_currency @order.duties_and_taxes_subsidized
                  %tr
                    %th
                      %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.tax')
                    %td= number_to_currency @order.tax_total
                  %tr
                    %th
                      %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.total_price')
                    %td
                      %strong= number_to_currency @order.total_price
                  %tr
                    %th
                      %span.data-pairs__name= t('workarea.admin.orders.attributes.totals.total_value')
                    %td= number_to_currency @order.total_value

app/views/workarea/admin/orders/global_e.html.haml
- @page_title = t('workarea.admin.orders.global_e.title', name: @order.name)

.view
  .view__header
    .grid.grid--middle.grid--right
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@order)
          %h1= link_to @order.name, url_for(@order)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@order)

  .view__container
    = render_cards_for(@order, :global_e)

  .view__container.view__container--narrow
    %h2
      = t('workarea.admin.orders.global_e.global_e_id')
      = @order.global_e_id
      %span (#{@order.currency})
    .section
      .grid.grid--huge
        .grid__cell.grid__cell--66-at-medium
          %h2= t('workarea.admin.orders.global_e.items.title')
          %table
            %thead
              %tr
                %th= t('workarea.admin.orders.global_e.items.product')
                %th.align-center= t('workarea.admin.orders.global_e.items.quantity')
                %th.align-right= t('workarea.admin.orders.global_e.items.international_pricing')
            %tbody
              - @order.items.each do |item|
                %tr
                  %td
                    .grid.grid--auto
                      .grid__cell
                        = link_to image_tag(product_image_url(item.image, :small), alt: item.product.name), catalog_product_url(item.product, sku: item.sku)
                      .grid__cell
                        %p= link_to item.product.name, catalog_product_path(item.product, sku: item.sku)
                        %p= item.sku
                        - if item.customizations.any?
                          - item.customizations.each do |name, value|
                            %p #{name.titleize}: #{value}
                        = append_partials('admin.order_attributes_item_details', item: item)
                  %td.align-center= item.quantity
                  %td.align-right
                    - item.international_price_adjustments.each do |adjustment|
                      %p
                        %strong= price_adjustment_description_for(adjustment)
                        %span= number_to_currency(adjustment.amount)

        .grid__cell.grid__cell--33-at-medium
          %h2= t('workarea.admin.orders.global_e.international_totals')
          %table
            %thead
              %tr
                %th
                %th.align-right= t('workarea.admin.field.amount')
            %tbody
              %tr
                %td
                  %p= t('workarea.admin.orders.cards.global_e.international_subtotal_price')
                %td.align-right= number_to_currency(@order.international_subtotal_price)
              - if @order.international_discount_adjustments.any?
                - @order.international_discount_adjustments.each do |adjustment|
                  %tr
                    %td
                      %span= adjustment.description.titleize
                    %td.align-right
                      - if adjustment.discount?
                        %strong= number_to_currency(adjustment.amount)
                      - else
                        %span= number_to_currency(adjustment.amount)
              - if @order.discount_adjustments.any?
                - @order.discount_adjustments.each do |adjustment|
                  %tr
                    %td
                      %span= adjustment.description.titleize
                    %td.align-right
                      - if adjustment.discount?
                        %strong= number_to_currency(adjustment.amount)
                      - else
                        %span= number_to_currency(adjustment.amount)
              %tr
                %td
                  %p= t('workarea.admin.orders.cards.global_e.international_shipping_total')
                %td.align-right= number_to_currency(@order.international_shipping_total)
              %tr
                %td
                  %p= t('workarea.admin.orders.cards.global_e.total_duties_price')
                %td.align-right= number_to_currency @order.total_duties_price
              %tr
                %td
                  %p= t('workarea.admin.orders.cards.global_e.total_price')
                %td.align-right= number_to_currency @order.international_total_price

  - if current_user.super_admin?
    .view__container
      %h2= t('workarea.admin.orders.global_e.raw_receive_order')
      .section
        %table.data-pairs
          %tbody
            - @order.global_e_api_events.receive_order.each do |key, value|
              - sanitized = sanitize_config_value(value)
              - if sanitized.present?
                %tr
                  %th
                    %span.data-pairs__name= key.to_s.titleize
                  %td
                    = sanitized

app/views/workarea/admin/orders/show.html.haml
- @page_title = @order.name

.view
  .view__header
    .grid.grid--middle.grid--right
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@order)
          %h1
            = @order.name
            - if @order.global_e_id.present?
              (#{@order.global_e_id})
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@order)

  .view__container
    = render_cards_for(@order)

  - if partials_to_append?('admin.order_show_workflow_bar_left') || partials_to_append?('admin.order_show_workflow_bar_right')
    .workflow-bar
      .grid
        .grid__cell.grid__cell--50
          .grid.grid--auto.grid--middle
            = append_partials('admin.order_show_workflow_bar_left', order: @order)
        .grid__cell.grid__cell--50
          .grid.grid--auto.grid--right.grid--middle
            = append_partials('admin.order_show_workflow_bar_right', order: @order)